import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../features/auth/context/authContext";
import { VeterinarianProvider } from "../features/common/context/VeterinarianContext";
import { OwnerProvider } from "../features/common/context/OwnerContext";
import { AnimalProvider } from "../features/common/context/AnimalsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <VeterinarianProvider>
          <OwnerProvider>
            <AnimalProvider>
              <body className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} antialiased`}>
                {children}
              </body>
            </AnimalProvider>
          </OwnerProvider>
        </VeterinarianProvider>
      </AuthProvider>
    </html>
  );
}
